### ISSUE TITLE
Class parsing fails if local variable name contains '<' or '>'

### ISSUE THREAD

**Issue by tth05** [staktrace/cafebabe#16]
The current implementation only allows these characters for constructors and static initializers, but the spec only forbids them for methods and not for fields or local variables. https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-4.html#jvms-4.2.2

This is a problem, because the kotlin compiler uses weird local variable names like this.
![image](https://user-images.githubusercontent.com/36999320/167262805-9761639b-f281-44ac-979a-4a6fc3d735d4.png)

Code which makes the wrong assumption:
https://github.com/staktrace/cafebabe/blob/main/src/attributes.rs#L600
Sample class:
[Kotlin.zip](https://github.com/staktrace/cafebabe/files/8645542/Kotlin.zip)

**Comment by staktrace** [comment]
Thanks for reporting! Are you planning to put up a PR to fix this, or would you prefer I do it?

**Comment by tth05** [comment]
I'm not really confident enough to do Rust PRs yet, I'll leave it up to you.
