### ISSUE TITLE
Consider backing class file data with an arena

### ISSUE THREAD

**Issue by i509VCB** [staktrace/cafebabe#28]
Much of the `constant_pool: Vec<Rc<ConstantPoolEntry<'a>>>` could be replaced by references into some arena type which owns the constant pool entries.

Although this causes a new problem: the constant pool arena must outlive the class file.

**Comment by staktrace** [comment]
What would be the point? The "arena" is currently the byte array holding the class file data, so I don't see any advantage to just copying it somewhere else.

**Comment by staktrace** [comment]
Closing for now, feel free to reopen if you have something else to add here.
