### ISSUE TITLE
[Suggestion] Derive more traits?

### ISSUE THREAD

**Issue by edgarogh** [staktrace/cafebabe#32]
A lot of structs would benefit from deriving more traits than just `Debug`. I'm stuck having to copy-paste structures of the library because I can't `Clone` them with the current design. This [checklist](https://rust-lang.github.io/api-guidelines/checklist.html) provides a few tips for good crate interoperability, and more specifically [a list of traits](https://rust-lang.github.io/api-guidelines/interoperability.html#c-common-traits) you may consider eagerly deriving/implementing on every struct where it makes sense.

I can submit a PR if you're interested.

**Comment by staktrace** [comment]
Yeah, fair point. I usually add the derives as I discover I need them. If you submit a PR to add more derived traits where they make sense, that would be very welcome. (My definition of "where they make sense" might differ from yours, but I can prune away derives from your PR if I feel they don't make sense).

**Comment by barereef** [comment]
I'd too would love to see Clone added to additional structs/enums – in particular Opcode at the moment.

**Comment by staktrace** [comment]
https://github.com/staktrace/cafebabe/pull/38 and other recent PRs add more traits. Marking this resolved. Feel free to submit PRs for additional traits as needed.
