### ISSUE TITLE
Typed RecordComponentEntry::descriptor

### ISSUE THREAD

**Issue by xitep** [staktrace/cafebabe#34]
hello, first of all many thanks for this library!

i wondered if there is any reason to not represent [RecordComponentEntry::descriptor](https://docs.rs/cafebabe/0.6.1/cafebabe/attributes/struct.RecordComponentEntry.html#structfield.descriptor) with a typed manner by a [FieldType](https://docs.rs/cafebabe/0.6.1/cafebabe/descriptor/enum.FieldType.html) instead of merely exposing it as a validated string; having it "typed" would nicely align with `ClassFile::fields` and `MethodDescriptor::parameters`. It could allow client code to unify the processing of the "field types." would you accept a PR? (right now i'm parsing the descriptor in my own code since `FieldType::parse` is "crate" private; it would greatly help me if `FieldType` exposed its parse method, implemented `FromStr` or similar.)

**Comment by staktrace** [comment]
I'd accept a PR to improve the situation. The FieldType stuff was contributed by somebody else after I stopped actively working on this crate, and I guess we just missed that the RecordComponentEntry::descriptor could use that.
