### ISSUE TITLE
Release of "threadsafe" feature in the near future?

### ISSUE THREAD

**Issue by Emilostuff** [staktrace/cafebabe#51]
Hey! This crate is absolutely awesome. I'm using it to write a JVM interpreter and I really love your API. However I want to share parsed ClassFile objects between threads, which is not possible due to the use of RC's and the like. I can see that you have implemented a threadsafe feature enabling exactly what I'm looking for, but it has not yet been released. Do you plan on releasing it soon or is it part of a larger change?

Thanks in advance!

**Comment by staktrace** [comment]
Yes, I'm happy to publish a new release if the threadsafe feature works for you. I was hoping to get some feedback on it to see if any tweaks were needed before publishing a release. If it works as-is I'm happy to release it. Let me know!

**Comment by Emilostuff** [comment]
Sounds good! I will try it out and get back to you.

**Comment by Emilostuff** [comment]
Everything seems to work fine; we can now share the same ClassFile between concurrent threads. Also, your changes to the API in FieldType/Descriptors is quite nice and easier to work with (even though it took some time to migrate our code to work with it).

**Comment by staktrace** [comment]
Great! I've published it as v0.8.0 to crates.io.
